### PR TITLE
fix: make Options.output a string type

### PR DESCRIPTION
**Pull request by RasPhilCo**
Fixes https://github.com/oclif/cli-ux/issues/135

### CODE REVIEW

**Comment by RasPhilCo** [comment]
@jgwhite

**Comment by jgwhite** [comment]
This seems good. As an alternative, could we override the type of `Table.Flags.output`?

```diff
  output: F.string({
    exclusive: ['no-truncate', 'csv'],
    description: 'output in a more machine friendly format',
    options: ['csv', 'json', 'yaml'],
- }),
+ }) as F.IOptionFlag<'csv' | 'json' | 'yaml' | undefined>,
```

**Comment by jgwhite** [comment]
Thanks @RasPhilCo!

**Comment by jbyrum** [comment]
What is the value of output --yaml?  It's not in a format the folks could then import correct? 

What is the value of csv?

**Comment by RasPhilCo** [comment]
@jbyrum I'm not sure I'm understand your question correctly, but this is list (table) output.

**Comment by jgwhite** [comment]
I may have caused some confusion here by cross-linking a bunch of PRs. This is the open source, general purpose CLI-UX repo.

**Pull request merged**
