### PR TITLE
feat: support for JSON/YAML parsable table output

### PR DESCRIPTION
**Pull request by ArchangelX360**
Still leveraging the greatness of table options, this enables output for
machine processing.

It is arguably a "table" output, the idea behind putting it inside the
 table class is mainly because it relies on same filtering/enhancing
 mechanism. I am open to suggestion for refactoring it into its own
 styled output.

### CODE REVIEW

**Comment by RasPhilCo** [comment]
I like this! But this is a breaking change. It's probably best to leave `--csv` as is, and add a hidden `--output` flag for now (I don't want to force all existing tables to have to adopt this atm).

**Comment by ArchangelX360** [comment]
Sure thing, that is a fair alternative! Will implement that in the upcoming days!

Thanks so much for the feedback :D

**Comment by ArchangelX360** [comment]
This should be better, they co-exist and `--csv` will set `--output=csv` internal. They are exclusive to prevent mixed usage. And thus is not a breaking change 😄.

**Comment by ArchangelX360** [comment]
Is there any other issue that is preventing merging this MR?

**Comment by RasPhilCo** [comment]
@ArchangelX360 I'm still concerned pushing out a depreciation to csv without notice (we use it extensively). How about `description: 'output in csv format [DEPRECATED, use --output=csv]'` -> `description: 'output in csv format [alias:  --output=csv]'` or something to that effect? We can deprecate in the next major bump.

**Comment by ArchangelX360** [comment]
Sure, I just pushed a change.

**Comment by ArchangelX360** [comment]
I don't understand this coverage check failure, the new bits of code are 100% tested. I think we are still good to merge that if that is fine with you @RasPhilCo.

**Comment by RasPhilCo** [comment]
great PR, thanks @ArchangelX360

**Comment by ArchangelX360** [comment]
@RasPhilCo thanks for merging! Any ETA on the release :smile:?

**Comment by RasPhilCo** [comment]
@ArchangelX360 Can release next Friday (we're in a once a year feature freeze).

**Comment by ArchangelX360** [comment]
Great thanks :)!

**Pull request merged**
