### PR TITLE
georgettica/make filtering more robust

### LINKED ISSUE #414: add better documentation to `--filter`
related to https://github.com/oclif/cli-ux/blob/4e5c19b3fd13493e09379d9e7da54b4bc7e4a2d3/src/styled/table.ts#L320

after reading https://github.com/oclif/cli-ux/blob/fd0ca55f2ae7096ea273592be35e071ee4ddcb0d/src/styled/table.ts#L64-L77
I was able to deduce the `!=` doesn't exist in the query language and a prepended `-` will do the trick

this could have been subverted if the help message would direct me to documentation on how the filter query language works

### PR DESCRIPTION
**Pull request by georgettica**
feat(filter): make filtering more robust

now filtering uses + and - for seperation so we can:

```
-name=foo
name=foo-age=bar
name=foo+age=bar
```

second iteration of #435
resolves #414

### CODE REVIEW

**Comment by georgettica** [comment]
Not passing and I am debugging locally.

Basically solved one issue (had a console output where it shouldn't have been)
But the most I am still investigating

**Comment by georgettica** [comment]
another change I was thinking of is adding a  `--seperators` that have to be only 2 and the first one is the negative one

```
npx ts-node examples/table.ts --seperators='!&' --filter !name=hello&company=bob
```

**Comment by georgettica** [comment]
@RodEsp WDYT?

**Comment by RodEsp** [comment]
Hey @georgettica, sorry for the delayed response. This is another breaking change, it will prevent users from filtering based on values that contain a `-`. I don't think this improves the filtering ability for the table and it also doesn't make its functionality any more obvious or intuitive.

I think the correct fix for #414 is simply to add documentation or allow for using `!=` as an operator. Anything that adds breaking changes is likely not going to get merged anytime soon.

**Comment by georgettica** [comment]
It's sad but ok.
It can also be done via using alternative seperators, this way we can change the seperator if it breaks something for you

I'll create a third PR with just doc changes

**Pull request closed without merging**
