### PR TITLE
Update chalk

### PR DESCRIPTION
**Pull request by G-Rath**
Based off #144 - updating `chalk` allows for even better deduplication, and is more performant (as they improved require speed as part of their major refactor).

### CODE REVIEW

**Comment by RasPhilCo** [comment]
Do you know if `chalk.enabled` is back supported? All our cli/plugins call it in tests.

**Comment by G-Rath** [comment]
@RasPhilCo I believe not; however, they should have their own dependency on Chalk which has its own version, unless the chalk api is exposed somewhere from here?

I'm happy to help with oclif, so happy to investigate further and to help update the other packages if needed.

**Comment by G-Rath** [comment]
So looking at [`plugin-help`](https://github.com/oclif/plugin-help/blob/master/package.json#L9) that has chalk as a dependency.

Would you like me to update chalk in other libraries as well?

**Comment by RasPhilCo** [comment]
We have a couple plugins doing `chalk.enabled = false` in tests (hoisted from cli-ux) that bumping cli-ux would break tests. But maybe we're the only ones. I think we should merge this but let me think on it for the night.

**Comment by G-Rath** [comment]
The only plugin I can find with this is [`plugin-not-found`](https://github.com/oclif/plugin-not-found/blob/master/test/hooks/not-found.test.ts#L1), which imports in from `@oclif/color`.

> maybe we're the only ones

I'm guessing you mean Salesforce/Heroku?

I'm not sure what you mean by "hosited from cli-ux", but a couple of common patterns that spring to mind are:

1. importing in chalk from `node_modules` without having it as a dependency

This can be resolved by just adding `chalk` as a dependency, which will ensure it's locked to the proper version (which is why this should always be done in the first place).

2. `cli-ux` is exporting `chalk` somewhere

I can't find this actually in the source code, but if that is what's happening, you can deprecate it by fudging the properties using a setter via `Object.defineProperty`.

You could also include in that a `console.warn` call to help track down where these usages are taking place.

-----

Happy to help where I can - it's awesome to see some traction on things 🙂 
Let me know if you'd like me to look into what other packages can be updated.

**Comment by RasPhilCo** [comment]
Thanks for the PR @G-Rath!

**Pull request merged**
